apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: bench-phi3-mini
spec:
  resource:
    instanceType: Standard_NV36ads_A10_v5
    count: 1
    labelSelector:
      matchLabels:
        apps: bench-phi3-mini
  inference:
    preset:
      name: phi-3-mini-128k-instruct
